/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tagtraum_japlscript_execution_CocoaScriptExecutor */

#ifndef _Included_com_tagtraum_japlscript_execution_CocoaScriptExecutor
#define _Included_com_tagtraum_japlscript_execution_CocoaScriptExecutor
#ifdef __cplusplus
extern "C" {
#endif
#undef com_tagtraum_japlscript_execution_CocoaScriptExecutor_MAX_RETURNVALUE_LOG_LENGTH
#define com_tagtraum_japlscript_execution_CocoaScriptExecutor_MAX_RETURNVALUE_LOG_LENGTH 1024L
/*
 * Class:     com_tagtraum_japlscript_execution_CocoaScriptExecutor
 * Method:    execute
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tagtraum_japlscript_execution_CocoaScriptExecutor_execute
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
